{% set name = "dipperpy" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dipperpy-{{ version }}.tar.gz
  sha256: 8cc5a5ac84b471817ab392c8b9faf9d2a0557055403b3eb79bbeab106c935123

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.0
    - setuptools
    - setuptools-scm
    - numpy
    - scipy
    - astropy
    - pip
  run:
    - python >=3.0


about:
  summary: Package performing spectral diagnostics and radiative transfer calculations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MWilson1
